name: publish extensions
on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          npm install -g @vscode/vsce
          npm install
      - name: format check
        run: npm run fmt:check
      - name: Publish extension
        id: publisher
        uses: sigma/vsce-publish-action@v0.0.2
        with:
          vsce_token: ${{ secrets.VSCE_TOKEN }}
          build_pkg: yes